<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="3e86f8a6454e" failures="1" tests="3" name="user-mike" time="89.583" errors="0" timestamp="2024-03-25T20:28:03 GMT">
  <testcase classname="com.kardockdock.tests.vendorportal.VendorPortalTest" name="loginTest" time="34.333"/>
  <testcase classname="com.kardockdock.tests.vendorportal.VendorPortalTest" name="dashboardTest" time="19.46">
    <failure type="java.lang.AssertionError" message="expected [3] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [10]
at com.kardockdock.tests.vendorportal.VendorPortalTest.dashboardTest(VendorPortalTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashboardTest -->
  <testcase classname="com.kardockdock.tests.vendorportal.VendorPortalTest" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- user-mike -->
